WITH DAILY_WEATHER AS (



    select 
    DATE(DATE_TIME) AS DAILY_WEATHER,
    WEATHER, 
    HUMIDITY, 
    PRESSURE, 
    TEMPERATURE,
    CLOUDS
    from {{ source('citi_analytics', 'weather_table') }}
), 
DAILY_WEATHER_AGG AS (

    select 
    DAILY_WEATHER,
    WEATHER,
    ROUND(AVG(HUMIDITY),2) AS AVG_HUMIDITY, 
    ROUND(AVG(PRESSURE),2) AS AVG_PRESSURE,  
    ROUND(AVG(TEMPERATURE),2) AS AVG_TEMP,
    ROUND(AVG(CLOUDS),2) AS AVG_CLOUDS

    from DAILY_WEATHER
    group by DAILY_WEATHER, WEATHER
    qualify ROW_NUMBER() OVER (PARTITION BY DAILY_WEATHER ORDER BY COUNT(WEATHER) DESC) = 1 
)

select *
from DAILY_WEATHER_AGG